[Xorg_fixesproto]
git-tree-sha1 = "85fa6b028ec74536909a8b3f091378bca25daa82"

    [[Xorg_fixesproto.download]]
    sha256 = "a430fa075414e84c615793d6e8f07d7b9f7e8d7c7717a4bb0efcfdea2788caea"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_fixesproto_jll.jl/releases/download/Xorg_fixesproto-v5.0.0+1/Xorg_fixesproto.v5.0.0.any.tar.gz"
